### ISSUE TITLE
Query returning only one document

### ISSUE THREAD

**Issue by felpsio** [BenAOlson/gatsby-source-firestore-easy#2]
My query is returning only one document.

Am I doing anything wrong or it may be a plugin issue?

gatsby-config:

```
{
      resolve: `gatsby-source-firestore-easy`,
      options: {
        adminCredential: {
          credential: require("./firebase-credential.json"),
          databaseURL: 'https://PROJECT.firebaseio.com',
        },
        collections: [
          'categories'
        ]
}
```

index.js:

```
export const query = graphql`
  {
    categories {
      id
      name
    },
  }
`;
```

PS: The problem is not related to my data because I can query all the documents using other plugins
PS2: I'm using the v1.0.0

**Comment by BenAOlson** [comment]
I think your query is not querying all documents in categories. I'm rusty with Gatsby, but I believe it should be something more like `allCategories`. You can go to `http://localhost:8000/___graphql` and test it out.

**Comment by felpsio** [comment]
Thanks. I didn't know about `http://localhost:8000/___graphql`

I was able to solve it using:
```
 {
    allCategories {
      edges {
        node {
          id
          name
        }
      }
    }
  }
```
