### ISSUE TITLE
Any chance for Gatsby 3?

### ISSUE THREAD

**Issue by denzo** [BenAOlson/gatsby-source-firestore-easy#4]
The current version is published with gatsby 2.24 and I am on 3.42

**Comment by felpsio** [comment]
I'm using this plugin with Gatsby 3.0.

You may need to add a resolution to your package.json or you can just fork and change only the dependencies.

I'm using yarn and didn't have a dependency problem with this plugin.

My dependencies:
```
"gatsby": "^3.1.1",
"gatsby-source-firestore-easy": "^1.0.0",
```

**Comment by BenAOlson** [comment]
The development dependency for Gatsby in this project is only for the sake of providing Typescript types during plugin development. It does not affect your Gatsby project in any way. To the best of my knowledge, this plugin is compatible with current versions of Gatsby. If you see any issues with a recent version of Gatsby, do let me know!

Closing this for now.

**Comment by BenAOlson** [comment]
Just for posterity, I think the issue here was a peer dependency, which I wasn't really thinking about. I hadn't looked at this plugin in a while when I wrote my previous comment.
