### ISSUE TITLE
Update gatsby peerDependencie to ^3.0.0

### ISSUE THREAD

**Issue by edriang** [BenAOlson/gatsby-source-firestore-easy#5]
Hey, could you please update gatsby peerDependencies to ^3.0.0? It works well with this version, but npm@^7 will complain with peerDependencies conflicts.

E.g.:
```
"peerDependencies": {
    "gatsby": "^2.19.38 || ^3.0.0"
}
```

**Comment by rdrnt** [comment]
Any updates on this?

**Comment by BenAOlson** [comment]
Hey, sorry, this slipped through the cracks. I'll try to address today

**Comment by rdrnt** [comment]
Thanks! Would it be possible to make it support v4 of Gatsby as well? I'm running it currently and there's no issues.

**Comment by BenAOlson** [comment]
New version with more permissive peer dep was published a little bit ago.

**Comment by BenAOlson** [comment]
Haven't heard anything, so I'm assuming no issues for anyone.
